--- #YAML:1.0
name:                HTML-Template-Convert-TT
version:             0.04
abstract:            perl extension for converting HTML::Template templates into Template Toolkit
license:             ~
author:              
    - A. D. Solovets <asolovets@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTML::Template:                2.9
    Template:                      2.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
